common:
  version: "1.0"
  socket:
    enabled: false
    port: 9081
  http:
    enabled: true
    port: 9080
  ws:
    enabled: false
    port: 9082
  storage:
    url: "${AUTH_STORAGE_URL}"
    token: "${AUTH_STORAGE_TOKEN}"
  sms:
    enabled: false
    url: "${SMS_URL}"
    master_key: "${SMS_MASTER_KEY}"
  email:
    enabled: false
    url: "${EMAIL_URL}"
    sender: "${EMAIL_SENDER}"
  encryption:
    salt: "${SALT}"
  auth:
    flood_limit: 5
    flood_duration: 30 #minutes
    url: "${AUTH_URL}"
tokens:
  token: "${AUTH_MASTER_TOKEN}"
  expiration:
    refresh_token: 604800000000000 # 7 * 24 hours
    access_token: 604800000000000 # 7 * 24 hours
  routine_execution_period:
    otp: 3600000000000 # 1 hour
    refresh_token: 3600000000000 # 1 hour
    access_token: 300000000000 # 5 minutes

default_role: '{
  "type": "default",
  "permissions": [
    {"microservice": "Crud","method": "create","required_params": [],"restricted_params": []},
    {"microservice": "crud","method": "read","required_params": [],"restricted_params": []},
    {"microservice": "crud","method": "update","required_params": [{"all":false,"param":"internal_id","values":["#internal_id"]}],"restricted_params": []},
    {"microservice": "crud","method": "delete","required_params": [{"all":false,"param":"internal_id","values":["#internal_id"]}],"restricted_params": []}
  ],
  "data": {
    "name": "Default",
    "alias": "default"
  }
}'

admin_role: '{
  "type": "admin",
  "permissions": [
    {"microservice": "Auth","method": "update_user","required_params": [],"restricted_params": []},
    {"microservice": "Auth","method": "get_users","required_params": [],"restricted_params": []},
    {"microservice": "Auth","method": "delete_users","required_params": [],"restricted_params": []},
    {"microservice": "Auth","method": "create_role","required_params": [],"restricted_params": []},
    {"microservice": "Auth","method": "update_roles","required_params": [],"restricted_params": []},
    {"microservice": "Auth","method": "delete_roles","required_params": [],"restricted_params": []},
    {"microservice": "Auth","method": "attach_role","required_params": [],"restricted_params": []},
    {"microservice": "Auth","method": "detach_role","required_params": [],"restricted_params": []},
    {"microservice": "Auth","method": "get_roles","required_params": [],"restricted_params": []},
  ],
  "data": {
    "name": "Admin",
    "alias": "admin"
  }
}'