apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}-deploy
  namespace: ${NAMESPACE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
      - name: ${SERVICE_NAME}-microservice
        image: ${IMAGE_NAME}
        ports:
